include("../default_config.jl")
lxm, lxo = @to_luxor_picture width=500 height=300 margin=30 begin
    a = APPoint(0.0, 0.0)
    b = APPoint(1.0, 0.0)
    c = APPoint(0.0, 1.0)
    a2 = APPoint(2.0, 3.0)
    b2 = APPoint(5.0, 3.0)
    c2 = APPoint(2.0, 7.0)
    @unbounded m = affine_map(a => a2, b => b2, c => c2)
    t = APTriangle(a, b, c)
    timg = m(t)
end
(; a, b, c, a2, b2, c2, m, t, timg) = lxo
@svg_doc(lxm, @__FILE__, begin
Luxor.fontsize(15)
gsave()
setline(1); setdash("dash")
sethue(julia_green)
path([APSegment(a, a2), APSegment(b, b2), APSegment(c, c2)], action=:stroke)
grestore()
sethue(julia_blue)
path(t, action=:stroke)
sethue(julia_purple)
path(timg, action=:stroke)
sethue(julia_red)
label("a", :SW, a); label("b", :S, b); label("c", :NW, c)
label("a'", :SW, a2); label("b'", :SE, b2); label("c'", :NW, c2)
path([a, b, c]); plot_point(julia_blue)
path([a2, b2, c2]); plot_point(julia_purple)
end)
