name = "Apollonius"
uuid = "54d4ec63-6df0-448b-bd74-e1b9ab51cc02"
authors = ["Jonatan Perren"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"

[extensions]
ApolloniusLuxorExt = "Luxor"

[compat]
LinearAlgebra = "1"
Luxor = "4"
julia = "1.10"
