include("../default_config.jl")
lxm, lxo = @to_luxor_picture width=500 height=280 margin=30 begin
    A, B = APPoint(0.0, 0.0), APPoint(6.0, 0.0)
    C = argmax(p -> p[2], intersection(APCircle2(A, 6.0), APCircle2(B, 6.0)))
    cA, cB = APCircle2(A, 6.0), APCircle2(B, 6.0)
end
(; A, B, C, cA, cB) = lxo
traces = [compass_trace(A, C; angle=pi / 4), compass_trace(B, C; angle=pi / 4)]
@svg_doc(lxm, @__FILE__, begin
Luxor.fontsize(15)
gsave()
setline(1); setdash(:dash)
sethue("gray80")
path([cA, cB], action=:stroke)
grestore()
gsave()
setline(1)
sethue(julia_green)
path(traces, action=:stroke)
grestore()
sethue(julia_purple)
path(APTriangle(A, B, C), action=:stroke)
path([A, B])
plot_point(julia_blue)
path([C])
plot_point(julia_purple)
sethue(julia_red)
label("A", :SW, A)
label("B", :SE, B)
label("C", :N, C)
end)
