include("../default_config.jl")
sz = @to_luxor_picture! width=500 height=320 margin=30 begin
    a, b, c = APPoint(0.0, 0.0), APPoint(5.0, 0.0), APPoint(1.0, 4.0)
    t = APTriangle(a, b, c)
    circ = circumcircle(t)
    G = centroid(t)
    I = incenter(t)
    foot = projection(c, APLine(a, b))
    height = APSegment(c, foot)
    right = APAngle2(foot, b, c)
end
@svg_doc(sz, @__FILE__, begin
Luxor.fontsize(15)
sethue(julia_purple); Luxor.setline(1.5)
path(circ, action=:stroke)
path(height, action=:stroke)
sethue(julia_green)
path(right; as=:rarc, radius=12, action=:stroke)
sethue(julia_blue); Luxor.setline(1.8)
path(t, action=:stroke)
path([a, b, c])
plot_point(julia_blue)
path([G, I, foot])
plot_point(julia_purple)
sethue(julia_red)
label("A", :SW, a)
label("B", :SE, b)
label("C", :N, c)
label("G", :NE, G)
label("I", :SE, I)
end)
