include("../default_config.jl")
sz = @to_luxor_picture! width=500 height=300 margin=45 begin
    A, B, C = APPoint(0.0, 0.0), APPoint(10.0, 0.0), APPoint(5.0, 6.0)
    t = APTriangle(A, B, C)
    base = APSegment(A, B)
    left = APSegment(A, C)
    right = APSegment(B, C)
    angA = APAngle2(A, B, C)
    angB = APAngle2(B, C, A)
end
G = centroid(t)
@svg_doc(sz, @__FILE__, begin
Luxor.fontsize(15)
sethue(julia_blue); Luxor.setline(1.5)
path(t, action=:stroke)
sethue(julia_purple)
path(marks(left; size=14); action=:stroke)
path(marks(right; size=14); action=:stroke)
path(marks(angA; count=2, size=34, gap=6); action=:stroke)
path(marks(angB; count=2, size=34, gap=6); action=:stroke)
path(arrow_head(base; at=0.2, size=12); action=:fill)
path(brace(base.p1, base.p2; height=12, side=:right); action=:stroke)
sethue(julia_red)
label("b", brace_anchor(base.p1, base.p2; height=12, side=:right)...)
for (v, n) in zip(vertices(t), ("A", "B", "C"))
    label(n, label_anchor(v, G)...)
end
end)
