include("../default_config.jl")
lxm, lxo = @to_luxor_picture width=500 height=300 margin=30 begin
    O = APPoint(0.0, 0.0)
    A = APPoint(3.0, 4.0)
    @unbounded l = APLine(O, A)
    d = APEquipollentVector(direction(l), O)
    onl = APPoint(6.0, 8.0)
    h = APSegment(O, APPoint(4.0, 0.0))
    ang = APAngle2(O, APPoint(3.0, 0.0), A)
end
(; O, A, l, d, onl, h, ang) = lxo
@svg_doc(lxm, @__FILE__, begin
Luxor.fontsize(15)
gsave()
setline(1)
sethue("gray80")
path(h, action=:stroke)
grestore()
sethue(julia_blue)
path(l, action=:stroke, extend=40)
path([O, A, onl]); plot_point(julia_blue)
sethue(julia_purple)
path(d; as=:arrow, action=:stroke)
path(marks(ang; size=40); action=:stroke)
sethue(julia_red)
label("53.13°", label_anchor(ang; dist=70)...)
label("direction(l)", :E, midpoint(O, A))
end)
