include("../default_config.jl")
sz = @to_luxor_picture! width=500 height=240 margin=20 begin
    P, Q, C = APPoint(1.0, 1.0), APPoint(6.0, 3.0), APPoint(3.0, 6.0)
    s = APSegment(P, Q)
    l = APLine(s)
    M = midpoint(s)
    lpa = parallel_through(l, C)
    lpe = perpendicular_through(l, C)
    lpb = perpendicular_bisector(s)
end
@svg_doc(sz, @__FILE__, begin
sethue(julia_blue)
    path(l, action=:stroke)
    sethue(julia_purple)
    path([lpa, lpe, lpb], action=:stroke)
    path([P,Q,C])
    plot_point(julia_blue)
    sethue(julia_red)
    label("Q", :NW ,Q)
    label("P", :NW ,P)
    label("C", :SW ,C)
end)
