include("../default_config.jl")
lxm, lxo = @prepare_to_picture width=500 height=240 margin=20 begin
    c = APCircle2(APPoint(0.0, 0.0), 5.0)
    p1, p2 = APPoint(0.0, 1.0), APPoint(-2.0, 0.0)
    arc = APCircularArc2(c, p1, p2)
    arc_rot = rotate(arc, 2pi/3)
    arc_hom = homothety(arc, -2.0)
end
(; c, p1, p2, arc, arc_rot, arc_hom) = lxo
@svg_doc(lxm, @__FILE__, begin
sethue(julia_purple)
path(APCircularSector2(only(marks(APAngle2(arc.circle.center, arc_rot.p1, arc.p1)))), action=:fill)
setdash(:dash)
path(APSegment(arc.circle.center, arc_rot.p1), action=:stroke)
path(APSegment(arc.circle.center, arc_hom.p1), action=:stroke)
sethue(julia_green)
path(APSegment(arc.circle.center, arc.p1), action=:stroke)
setdash(:solid)
sethue(julia_blue)
path(arc, action=:stroke)
sethue(julia_purple)
path([arc_rot, arc_hom], action=:stroke)
sethue("white"); path([arc_rot.p1, arc_hom.p1], action=:fillpreserve); sethue(julia_purple); strokepath()
sethue("white"); path([arc.circle.center, arc.p1], action=:fillpreserve); sethue(julia_blue); strokepath()
end)
