include("../default_config.jl")
lxm, lxo = @prepare_to_picture width=500 height=240 margin=20 begin
    c1 = APCircle2(APPoint(0.0, 0.0), 3.0)
    c2 = APCircle2(APPoint(8.0, 0.0), 2.0)
    c3 = APCircle2(APPoint(3.0, 6.0), 4.0)
    ra1 = radical_axis(c1, c2)
    ra2 = radical_axis(c2, c3)
    ra3 = radical_axis(c3, c1)
    rc = radical_center(c1, c2, c3)
    rcirc = radical_circle(c1, c2, c3)
end
(; c1, c2, c3, ra1, ra2, ra3, rc, rcirc) = lxo
@svg_doc(lxm, @__FILE__, begin
sethue("gray80")
setdash(:dash)
path(APSegment(c1.center, c3.center), action=:stroke)
path(APSegment(c2.center, c3.center), action=:stroke)
path([ra2, ra3], action=:stroke)
sethue(julia_purple)
path(APSegment(c1.center, c2.center), action=:stroke)
setdash(:solid)
sethue(julia_blue)
path([c1,c2,c3], action=:stroke)
sethue(julia_purple)
path(rcirc, action=:stroke)
path(ra1, action=:stroke)
sethue("white"); path(rc, action=:fillpreserve); sethue(julia_purple); strokepath()
sethue("white"); path([c1.center, c2.center, c3.center], action=:fillpreserve); sethue(julia_blue); strokepath()
end)
