include("../default_config.jl")
lxm, lxo = @prepare_to_picture width=500 height=240 margin=20 begin
    P = APPoint(0.0, 0.0)
    @unbounded inv5 = invert(P; k=5.0)
    circ = APCircle2(P, 5.0)
    l1 = APLine(APPoint(2.0, 0.0), APPoint(2.0, 1.0))
    l2 = APLine(APPoint(-3.0, 0.0), APPoint(-3.0, 1.0))
    t1, t2 = map(inv5, [l1, l2])
end
(; P, circ, l1, l2, t1, t2) = lxo
@svg_doc(lxm, @__FILE__, begin
sethue("gray80")
setdash(:dash)
path(circ, action=:stroke)
sethue(julia_blue)
path(t1, action=:stroke)
setdash(:solid)
path(l1, action=:stroke)
sethue(julia_green)
path(l2, action=:stroke)
setdash(:dash)
path(t2, action=:stroke)
setdash(:solid)
sethue("white"); path(P, action=:fillpreserve); sethue(julia_blue); strokepath()
end)
