include("../default_config.jl")
lxm = @prepare_to_picture! width=500 height=240 margin=20 begin
    p1, p2 = APPoint(0.0, -5.0), APPoint(0.0, 5.0)
    l = APLine(p1, p2)
    hp = APHalfPlane2(l, APPoint(1.0, 0.0))
    p3, p4 = APPoint(-6.0, 0.0), APPoint(6.0, 0.0)
    p5, p6 = APPoint(-6.0, 3.0), APPoint(6.0, 3.0)
    l1 = APLine(p3, p4)
    l2 = APLine(p5, p6)
    st = APStrip2(l1, l2)
    u = intersection(hp, st)
end
@svg_doc(lxm, @__FILE__, begin
gsave()
sethue("gray80"); setdash("dash")
path(l, action=:stroke, extend=10)
path([l1, l2], action=:stroke, extend=10)
grestore()
sethue(julia_purple); setline(3)
path(u, action=:stroke, extend=10)
end)
