include("../default_config.jl")
sz = @to_luxor_picture! width=500 height=240 margin=20 begin
    A, B, C = APPoint(0.0,0), APPoint(10,0), APPoint(7,5)
    triangle =  APTriangle(A, B, C)
    G = centroid(triangle)
    O = circumcenter(triangle)
    I = incenter(triangle)
    H = orthocenter(triangle)
    l = euler_line(triangle)
    lados = APLine.(sides(triangle))
    @unbounded cc = circumcircle(triangle)
    ic = incircle(triangle)
    iv = projection.(I, lados)
    npc = nine_point_circle(triangle)
    npc_c = nine_point_center(triangle)
    ep = collect(euler_points(triangle))
    ips = reduce(vcat, intersection.(npc, lados))
end
@svg_doc(sz, @__FILE__, begin
sethue("gray80")
gsave()
setline(1)
setdash(:dash)
path([cc, ic], action=:stroke)
path(APSegment(O, A), action=:stroke)
path(APSegment(I, iv[2]), action=:stroke)
grestore()
sethue(julia_purple)
path([l, npc], action=:stroke)
path([G,O,I,H])
plot_point(julia_purple)
sethue(julia_blue)
path(triangle, action=:stroke)
path([A,B,C])
plot_point(julia_blue)
path(iv)
path(ips)
newsubpath()
path(npc_c)
plot_point("gray80")
path(ep)
plot_point(julia_purple)
end)
