using Apollonius
using Documenter
DocMeta.setdocmeta!(Apollonius, :DocTestSetup, :(using Apollonius); recursive=true)
makedocs(;
    modules=[Apollonius],
    authors="Jonatan Perren",
    sitename="Apollonius.jl",
    format=Documenter.HTML(;
        canonical="https://gxono.github.io/Apollonius.jl",
        edit_link="master",
        assets=String[],
        size_threshold_ignore=["api.md"],
        example_size_threshold=16 * 1024,
        size_threshold_warn=400 * 1024,
        size_threshold=800 * 1024,
        search_size_threshold_warn=1024 * 1024,
    ),
    pages=[
        "Home" => "index.md",
        "Tutorials" => [
            "Getting Started" => "getting_started.md",
            "Workflow: From Construction to Figure" => "workflow.md",
            "Euclid, Book I" => "euclid.md",
        ],
        "Core Concepts" => [
            "Conventions & FAQ" => "conventions.md",
            "Numbers & Tolerances" => "numbers.md",
            "Types & Operations" => "types.md",
            "Predicates" => "predicates.md",
            "Measurements & Queries" => "measurements.md",
            "Intersections" => "intersections.md",
        ],
        "Points, Lines & Rays" => [
            "Creating Them" => "points_lines_creating.md",
            "Direction & Transforms" => "points_lines_transforms.md",
            "Angles" => "points_lines_angles.md",
            "Special Points & Curves" => "points_lines_special.md",
        ],
        "Circles" => [
            "Basics" => "circles_basics.md",
            "Inversion" => "circles_inversion.md",
            "How They Relate" => "circles_relations.md",
            "Arcs" => "circles_arcs.md",
            "Sectors, Segments & Curvilinear Chains" => "circles_regions.md",
        ],
        "Conics: Ellipse, Parabola & Hyperbola" => [
            "Ellipse, Parabola & Hyperbola" => "conics_basics.md",
            "Building From Other Data" => "conics_constructors.md",
            "Tangents, Duality & Arcs" => "conics_tangents_arcs.md",
            "Transforming & Fitting" => "conics_transform_fit.md",
        ],
        "Triangles & Triangle Centers" => [
            "The Classical Centers" => "triangles_classical_centers.md",
            "Barycentric & Trilinear Coordinates" => "triangles_coordinates.md",
            "Vertex-Indexed Lines" => "triangles_vertex_lines.md",
            "Further Named Centers" => "triangles_named_centers.md",
            "Steiner & Other Inellipses" => "triangles_inellipses.md",
            "Derived Triangles" => "triangles_derived.md",
            "Inscribed Squares & Triangles on a Segment" => "triangles_on_segment.md",
        ],
        "Polygons & Bounding Boxes" => [
            "Measurements & Operations" => "polygons_operations.md",
            "Bounding Boxes" => "polygons_bounding_boxes.md",
            "Named Constructors & Quadrilaterals" => "polygons_constructors.md",
        ],
        "Tangency & Apollonius Problems" => [
            "The Ten Apollonius Problems" => "tangency_basics.md",
            "Interstices" => "tangency_interstices.md",
            "Fixing a Point, Radius or Center" => "tangency_fixed.md",
        ],
        "Unbounded Regions" => "unbounded_sets.md",
        "Affine Maps" => "affine_maps.md",
        "Drawing & Illustration" => [
            "Drawing with Luxor.jl" => "drawing_basics.md",
            "What Each Type Builds" => "drawing_shapes.md",
            "Clipping, Dimensions & Reversing" => "drawing_advanced.md",
            "The Package Logo & Name Collisions" => "drawing_appendix.md",
            "Marks: `tangent_at` & `marks`" => "decorations_marks.md",
            "Arrowheads & Braces" => "decorations_arrows_braces.md",
            "Labels, Guides & Grids" => "decorations_labels_guides.md",
            "Compass & Ruler Constructions" => "constructions.md",
            "Macros: Sizing a Picture" => "macros_picture.md",
            "Macros: Transforming Shapes" => "macros_transforms.md",
        ],
        "Cookbook" => [
            "Points & Segments" => "cookbook_points_segments.md",
            "Lines" => "cookbook_lines.md",
            "Circles" => "cookbook_circles.md",
            "Tangent Circles" => "cookbook_tangent_circles.md",
            "Triangles" => "cookbook_triangles.md",
            "Polygons" => "cookbook_polygons.md",
            "Conics" => "cookbook_conics.md",
            "Building & Moving Shapes" => "cookbook_building_moving.md",
            "Checking & Drawing Recipes" => "cookbook_utility.md",
        ],
        "Examples" => "examples.md",
        "API Reference" => "api.md",
    ],
)
deploydocs(;
    repo="github.com/gxono/Apollonius.jl",
    devbranch="master",
)
